### PR TITLE
Using class instead of object for registering ServletJaxRsContextFactoryProvider

### PR DESCRIPTION
**Pull request by ganeshs**
Raising #38 for master

### CODE REVIEW

**Comment by victornoel** [comment]
@ganeshs can you rebase on master? just fixed the dependencies :)

**Comment by ganeshs** [comment]
Thanks. I see the build passing now.

**Comment by victornoel** [comment]
thanks a lot @ganeshs

**Comment by ganeshs** [comment]
@victornoel just wanted to check when the next release is planned.

**Comment by victornoel** [comment]
Damned! thx for the feedback. If you manage to introduce a test that currently fail, I would love it!

As for the release, once we are sure it's ok, it can happen very fast :)

Should I revert or we can simply work on top of this?

**Comment by ganeshs** [comment]
@victornoel We will have to revert this fix. The fix is better done in the jax-rs-pac4j module. I already see similar fix done for grizzly jaxrs module.

**Comment by ganeshs** [comment]
Doing the fix from `GrizzlyJaxRsContextFactoryProvider` breaks resteasy tests but works for others.

**Comment by victornoel** [comment]
@ganeshs ok, I will revert the PRs. Meanwhile, could you open an issue describing clearly the problem in dropwizard-pac4j or jax-rs-pac4j before we start to think of a solution?  Thanks :)

**Pull request merged**
